site_name: 2020_5AI_Team5

nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification Plan': 'Software_requirements.md'
    - 'Project Model Canvas': 'Project Model Canvas.md'
    - 'SoftwareProject Management Plan': 'SoftwareProject Management Plan.md'
    - 'Businnes Model Canvas': 'Project Charter.pdf'
   
    
theme:
    name: readthedocs

