site_name: 2020_5AI_Team5

nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification Plan': 'Software_requirements.md'
    - 'Project Model Canvas': 'Project Model Canvas.md'
    - 'Software Project Management Plan': 'Software Project Management Plan.md'
    - 'Businnes Model Canvas': 'Project Charter.md'
    - 'System Documentation': 'System Documentation.md'
    - 'Test Case Specification': 'Test Case Specification.md'
    - 'Iteration Plan': 'Iteration Plan.md'
    - 'Memorandum Of Understanding': 'Memorandum Of Understanding.md'
    - 'Release Plan': 'Release Plan.md'
    - 'User Guide': 'User Guide.md'
    
theme:
    name: readthedocs

